### ISSUE TITLE
The createModel() function only returns null

### ISSUE THREAD

**Issue by matheustdo** [milan-fabian/java-fingerprint-sensor#3]
The _createModel()_ function is returning null even if there is a fingerprint placed on sensor. It's making impossible the use of _saveModel(byte[] model, int number)_ function, as well as there are no more ways to get models back and store it elsewhere.

**Comment by milan-fabian** [comment]
You have to call _hasFingerprint()_ first and only if it returns true, then call _createModel()_. The sensor needs two samples (one from _hasFingerprint()_ and one from _createModel()_) in order to generate the model.
